name: next-playground
services:
  next-playground:
    container_name: next-playground
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: "npm run dev"
    volumes:
      - ../:/workspace/next-playground
    ports:
      - "3001:3000"
    tty: true
